name: ...begins in wonder
markdown: redcarpet
pygments: true
github: www.github.com/kookster
about: code, poetry, philosophy, folly (Andrew Kuklewicz)
urls:
    - text: github
      url: https://github.com/kookster
    - text: email
      url: mailto:andrew@beginsinwonder.com
